# Generated by Django 2.0.5 on 2018-06-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='status',
            new_name='extrovertion',
        ),
    ]
