# Generated by Django 2.0.5 on 2018-06-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_input_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='height',
        ),
        migrations.RemoveField(
            model_name='input',
            name='waist',
        ),
        migrations.AddField(
            model_name='input',
            name='relevance',
            field=models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1),
        ),
        migrations.AddField(
            model_name='input',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1),
        ),
    ]
