# Generated by Django 2.0.5 on 2018-06-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_input_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='type_select',
            field=models.CharField(choices=[('1', 'Unfriendly'), ('2', 'Unfriendly'), ('3', 'Unfriendly'), ('4', 'Unfriendly'), ('5', 'Friendly')], default='1', max_length=1),
        ),
    ]
