# Generated by Django 2.0.5 on 2018-06-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180628_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='input',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1),
        ),
    ]
