# Generated by Django 2.0.5 on 2018-06-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180628_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='extrovertion',
        ),
        migrations.AddField(
            model_name='input',
            name='type_select',
            field=models.BooleanField(default=True, verbose_name='Complete'),
        ),
    ]
